Repository logto-io/toolkit, pull requests merged in 2022-09, with the labels that each got.

#3 chore: rename packages
  commitlint.config.js
  packages/connector-kit/package.json
  packages/connector-kit/src/types.ts
  packages/core-kit/package.json
  pnpm-lock.yaml
Labels: chore, size/s

#4 chore(core,connector): update GetUserInfo response and expose zod utils
  packages/connector-kit/src/types.ts
  packages/core-kit/src/utilities/index.ts
Labels: chore, size/xs

#5 chore: add missing file
  merge-eslint-reports.js
Labels: chore, size/s

#6 chore: remove react-router util and bump @silverhand/essentials
  packages/connector-kit/package.json
  packages/core-kit/package.json
  packages/core-kit/src/utilities/index.ts
  packages/core-kit/src/utilities/react-router.ts
  pnpm-lock.yaml
Labels: chore, size/s

#7 chore(core): rename preserved scope to reserved scope
  packages/core-kit/src/scope.ts
Labels: chore, size/xs

#8 chore(core): add jest and sample test cases
  .github/workflows/main.yml
  package.json
  packages/core-kit/jest.config.ts
  packages/core-kit/package.json
  packages/core-kit/src/utilities/string.test.ts
  packages/core-kit/src/utilities/zod.test.ts
  packages/core-kit/tsconfig.json
  pnpm-lock.yaml
Labels: chore, size/s

#11 fix: remove unused file utils to avoid importing fs in browser
  packages/core-kit/src/utilities/file.ts
  packages/core-kit/src/utilities/index.ts
Labels: bugfix, size/s

#13 Revert "feat(language,core,connector)!: init @logto/language-kit package"
  commitlint.config.js
  packages/connector-kit/package.json
  packages/connector-kit/src/types.ts
  packages/core-kit/package.json
  packages/core-kit/src/language.ts
  packages/language-kit/jest.config.ts
  packages/language-kit/package.json
  packages/language-kit/src/const.ts
  packages/language-kit/src/index.ts
  packages/language-kit/src/type.test.ts
  packages/language-kit/src/type.ts
  packages/language-kit/tsconfig.build.json
  packages/language-kit/tsconfig.json
  pnpm-lock.yaml
Labels: size/m

#15 fix(core,language): avoid using path aliases
  packages/core-kit/src/language.ts
  packages/core-kit/tsconfig.json
  packages/language-kit/tsconfig.json
Labels: bugfix, size/s

#16 chore: remove reverted commit content from CHANGELOG.md
  packages/connector-kit/CHANGELOG.md
  packages/core-kit/CHANGELOG.md
  packages/language-kit/CHANGELOG.md
Labels: chore, size/s

#17 refactor(core): improve redirect URI validation
  packages/core-kit/src/regex.ts
Labels: enhancement, size/xs
