Repository logto-io/toolkit, pull requests merged in 2022-12, with the labels that each got.

#42 chore(core): remove deprecated `LanguageKey` type
  packages/core-kit/src/index.ts
  packages/core-kit/src/language.ts
Labels: chore, size/s

#43 chore: build dual bundle
  packages/connector-kit/package.json
  packages/connector-kit/rollup.config.js
  packages/connector-kit/tsconfig.json
  packages/core-kit/package.json
  packages/core-kit/rollup.config.js
  packages/core-kit/src/index.ts
  packages/core-kit/src/utilities/index.ts
  packages/core-kit/src/utilities/string.test.ts
  packages/core-kit/src/utilities/url.test.ts
  packages/core-kit/src/utilities/url.ts
  packages/core-kit/src/utilities/zod.test.ts
  packages/core-kit/tsconfig.json
  packages/language-kit/package.json
  packages/language-kit/rollup.config.js
  packages/language-kit/src/index.ts
  packages/language-kit/src/type.ts
  packages/language-kit/src/utility.test.ts
  packages/language-kit/src/utility.ts
  packages/language-kit/tsconfig.json
  pnpm-lock.yaml
Labels: chore, size/m

#45 fix: exports info and lock dep version
  packages/connector-kit/package.json
  packages/core-kit/package.json
  packages/language-kit/package.json
  pnpm-lock.yaml
Labels: bugfix, size/s

#46 chore: update GetAuthorizationUri and GetUserInfo
  packages/connector-kit/src/types.ts
Labels: chore, size/xs

#47 chore: update README
  README.md
Labels: chore, size/xs
