Repository logto-io/toolkit, pull requests merged in 2022-11, with the labels that each got.

#35 feat: update connector metadata types and add corresponding type guards
  packages/connector-kit/src/types.ts
Labels: feature, size/s

#36 fix: make standard connectors display name configurable
  packages/connector-kit/src/types.ts
Labels: bugfix, size/xs

#37 fix: hot fix the check on whether an element exists in array
  packages/connector-kit/src/types.ts
Labels: bugfix, size/xs

#38 refactor: use ESM
  package.json
  packages/connector-kit/package.json
  packages/connector-kit/src/index.ts
  packages/connector-kit/tsconfig.json
  packages/core-kit/declaration/index.ts
  packages/core-kit/jest.config.ts
  packages/core-kit/package.json
  packages/core-kit/src/index.ts
  packages/core-kit/src/language.ts
  packages/core-kit/src/utilities/index.ts
  packages/core-kit/src/utilities/string.test.ts
  packages/core-kit/src/utilities/url.test.ts
  packages/core-kit/src/utilities/url.ts
  packages/core-kit/src/utilities/zod.test.ts
  packages/core-kit/tsconfig.json
  packages/language-kit/jest.config.ts
  packages/language-kit/package.json
  packages/language-kit/src/index.ts
  packages/language-kit/src/type.ts
  packages/language-kit/src/utility.test.ts
  packages/language-kit/src/utility.ts
  packages/language-kit/tsconfig.json
  pnpm-lock.yaml
Labels: enhancement, size/m

#39 fix(core): declarations
  packages/core-kit/declaration/index.ts
Labels: bugfix, size/xs

#40 refactor: use CJS
  packages/connector-kit/package.json
  packages/connector-kit/tsconfig.json
  packages/core-kit/package.json
  packages/core-kit/src/index.ts
  packages/core-kit/src/language.ts
  packages/core-kit/src/utilities/index.ts
  packages/core-kit/src/utilities/string.test.ts
  packages/core-kit/src/utilities/url.test.ts
  packages/core-kit/src/utilities/url.ts
  packages/core-kit/src/utilities/zod.test.ts
  packages/core-kit/tsconfig.json
  packages/language-kit/package.json
  packages/language-kit/src/index.ts
  packages/language-kit/src/type.ts
  packages/language-kit/src/utility.test.ts
  packages/language-kit/src/utility.ts
  packages/language-kit/tsconfig.json
  pnpm-lock.yaml
Labels: enhancement, size/s

#41 feat(connector): add continue message type
  packages/connector-kit/src/types.ts
Labels: feature, size/xs
