Repository logto-io/toolkit, pull requests merged in 2022-10, with the labels that each got.

#19 refactor(core): add regex and utils to validate redirect uris
  packages/core-kit/src/regex.ts
  packages/core-kit/src/utilities/url.test.ts
  packages/core-kit/src/utilities/url.ts
Labels: enhancement, size/s

#20 refactor(core): update theme color tokens
  packages/core-kit/scss/_console-themes.scss
Labels: enhancement, size/xs

#21 chore: allow renovate deps commit
  commitlint.config.js
Labels: chore, size/xs

#22 chore(core): remove eslint-config-react from core-kit
  packages/core-kit/package.json
  pnpm-lock.yaml
Labels: chore, size/xs

#23 fix: export url utilities in index file
  packages/core-kit/src/utilities/index.ts
Labels: bugfix, size/xs

#25 chore: add stylelint to CI
  .github/workflows/main.yml
  package.json
  packages/core-kit/package.json
  pnpm-lock.yaml
Labels: chore, size/xs

#28 fix: language tag `jp`
  packages/language-kit/src/const.ts
Labels: bugfix, size/xs

#29 refactor(language): add language code
  packages/language-kit/src/const.ts
Labels: enhancement, size/s

#31 chore: update package.json
  packages/connector-kit/package.json
  packages/core-kit/package.json
  packages/language-kit/package.json
Labels: chore, size/s

#32 chore: update renovate.json
  renovate.json
Labels: chore, size/xs
